name: custom_image_cutter
description: CustomImageCutter is a powerful and versatile package designed to simplify the process of customizing image crops in an intuitive way.
version: 1.1.5
repository: https://github.com/fmn-learning/custom-image-cutter

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
